### ISSUE TITLE
Window not closing

### ISSUE THREAD

**Issue by Akascape** [littlewhitecloud/CustomTkinterTitlebar#31]
In IDLE mode, the close button is not working.

https://github.com/littlewhitecloud/CustomTkinterTitlebar/blob/cfe3c32af75b898473e82c532bfce8a5fb337066/CustomTkinterTitlebar/titlebar.py#L85-L91

**Fix**

```python
 self._titleexit.config(
            bd=0,
            activebackground=self.colors["%sexit_bg" % self.theme],
            width=44,
            image=self.close_hov_img,
            relief=FLAT,
            command=self.destroy, # quit sometimes doesn't work
        )
```

**Comment by littlewhitecloud** [comment]
I am going to rebuild it because the code is really laggy LOL
