### ISSUE TITLE
Windows 11 下最大化按钮没有绑定一个特殊的事件

### ISSUE THREAD

**Issue by Xiaokang2022** [littlewhitecloud/CustomTkinterTitlebar#45]
Windows 11 操作系统下，对于一般窗口而言，鼠标移至最大化按钮上悬停一会儿时（按下组合键 <kbd>Win+Z</kbd> 也可触发），会弹出一个分屏的小窗，但这个功能在这个自定义标题栏中是没有的。

<img width="215" alt="image" src="https://github.com/littlewhitecloud/CustomTkinterTitlebar/assets/100004682/d5a3963b-287c-4288-8330-b1d2fc685185">

不知作者是否能在未来加入此功能？

**Comment by littlewhitecloud** [comment]
这个我其实之前考虑过，但是添加起来有点麻烦，所以没有搞

**Comment by littlewhitecloud** [comment]
主要是实现这个功能需要在handle函数里面判断WM_NCHITTEST，然后检查是否悬停在最大化按钮上然后再返回一个HTMAXBUTTON值。
由于我这个水平太差了，我写的这个回调函数其实是从windnd那边魔改来的，不是很理解意思，所以返回值以后会出现程序没有回调的问题。

**Comment by Xiaokang2022** [comment]
@littlewhitecloud 我的想法是，先判定操作系统版本，再判定是否悬停，最后直接对程序触发 <kbd>Win+Z</kbd> 即可，其它的就不用考虑了。不知道这个方法是否可行？

**Comment by littlewhitecloud** [comment]
> @littlewhitecloud 我的想法是，先判定操作系统版本，再判定是否悬停，最后直接对程序触发 Win+Z 即可，其它的就不用考虑了。不知道这个方法是否可行？

上次试过，就是绑定了事件以后有点问题。
如果感兴趣的话，你可以开一个pr来实现以下。（虽然我可能会在之后添加）

**Comment by Xiaokang2022** [comment]
@littlewhitecloud 好的，有空我也试一下。

另外，关于您另外的一个项目我也提了个 Issue，不妨处理一下😅？https://github.com/littlewhitecloud/win32style/issues/3

**Comment by littlewhitecloud** [comment]
> @littlewhitecloud 好的，有空我也试一下。
> 
> 另外，关于您另外的一个项目我也提了个 Issue，不妨处理一下😅？[littlewhitecloud/win32style#3](https://github.com/littlewhitecloud/win32style/issues/3)

好的
